### PR TITLE
Use Elastic stack 7.5.0 in Malcolm

### PR DESCRIPTION
**Pull request by mmguero**

### CODE REVIEW

**Comment by zmink-pxc** [comment]
Have an issue running the install script from the git repo on this branch.

image

**Comment by zmink-pxc** [comment]
Looks like the f's just need to be removed.  Working after I remove them

**Comment by mmguero** [comment]
> Looks like the f's just need to be removed. Working after I remove them

Those are [f-string](https://www.python.org/dev/peps/pep-0498/#how-to-denote-f-strings). Has to do with the version of python, particularly python 3, that your system's treating as default. However I was trying to make this script python-agnostic, so good catch on that, I'll do it a more backwards compatible way

**Comment by mmguero** [comment]
Commit 33f7598b which I've pushed to all of the branches resolves that.

**Pull request merged**
