### PR TITLE
Adds initial support for building Hedgehog RPI images

### PR DESCRIPTION
**Pull request by aut0exec**
## 🗣 Description ##

Initial support for creating an RPI Hedgehog image.

## 💭 Motivation and context ##

There was a request for this functionality and an [open issue](https://github.com/idaholab/Malcolm/issues/250 ) tracked on the INL Malcolm repo.

Raspberry Pi's are cheap and readily available these days and resources on the RPI 4 8GB are likely sufficient to support running a Hedgehog sensor. The Debian process used to build base Debian RPI images was used and then the necessary additions to build Debian into Hedgehog were added/installed via a chroot.

Raspberry Pi, Hedghehog ARM sensor

## 🧪 Testing ##

Full builds were done and tested on a RPI 4 8GB model. An actual RPI 4 sensor was setup and connected to a Malcolm instance via the guide [here](https://malcolm.fyi/docs/malcolm-hedgehog-e2e-iso-install.html). No further testing beyond the E2E guide has been performed thus far. More testing recommended to ensure that the RPI image contains all the necessary configurations to function properly in a production setup.

## ✅ Pre-approval checklist ##

- [✅  ] This PR has an informative and human-readable title.
- [ ✅ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ✅] All relevant type-of-change labels have been added.
- [✅ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ✅] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ✅] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

### CODE REVIEW

**Comment by mmguero** [comment]
I've pulled the commit(s) from this branch into my development fork, when it's included in the next Malcolm release I'll come back here and close this PR.

**Comment by aut0exec** [comment]
Added a fix for the console not displaying UTF-8 properly and ensure that the sd-card is re-partitioned on first boot of the pi.

**Comment by mmguero** [comment]
Thanks I've pulled your update into my release testing branch and will test it out first thing Monday.

**Comment by mmguero** [comment]
commits included in and superceded by #297

**Pull request closed without merging**
