### PR TITLE
Update to install.py to omit Path Traversal

### PR DESCRIPTION
**Pull request by bhaskarvilles**
Cross-site Scripting (XSS) and Path Traversal bug fixes.

### CODE REVIEW

**Comment by mmguero** [comment]
Where are `secure_fullpath` and `secure_installPath` defined? I'm seeing their use in these scripts but no definition.

**Comment by mmguero** [comment]
And, as a result, e.g.:

```
NameError: name 'secure_fullpath' is not defined
```

**Comment by bhaskarvilles** [comment]
Can you fix this error ?

**Comment by mmguero** [comment]
I don't know what you're talking about. You've submitted a non-working pull-request. You reference functions (variables?) that don't exist.

**Comment by mmguero** [comment]
Closing, please re-open if you've got more details about what it is you're trying to do.

**Pull request closed without merging**
